swagger: "2.0"
info: 
  title: "SubscriptionBilling"
  description: "This is an API to manage subscription billing"
  version: "1.0.0"
host: "127.0.0.1:5000"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
securityDefinitions: 
  bearerAuth: 
    type: apiKey
    name: Authorization
    in: header

paths: 

  /users/login: 

    post:
      tags: 
        - Users 
      summary: "Login endpoint, (generates token)"
      description: "Validates user credentials, generates and returns a role specific token."
      parameters: 
        - in: "body"
          name: "body"
          description: "Login Credentials"
          required: true
          schema: 
            $ref: "#/definitions/LoginCredentials"
      responses: 
        201: 
          description: "Login successful"
          schema: 
            $ref: "#/definitions/LoginResponse"
          examples: 
            application/json: 
              token: "sjkdhcshcyg734yrshdcb..."
              message: "Login successful"
              status: "success"

  /users: 
    
    post: 
      tags: 
        - Users 
      summary: "Endpoint to create/register a new user"
      description: "Endpoint to create a new user in SubscriptionBilling, emails must be unique"
      parameters: 
        - in: "body"
          name: "body"
          description: "Information required to create a new user"
          required: true
          schema: 
            $ref: "#/definitions/CreateUserPayload"
      responses: 
        201: 
          description: "Successful User Creation"
          schema: 
            $ref: "#/definitions/CreateUserResponse"
          examples: 
            application/json: 
              id: 1
              name: "John Doe"
              email: "jd@gmail.com"
              role: "admin"
    get: 
      tags: 
        - Users 
      summary: "Endpoint to get all users"
      description: "Returns paginated list of all users, token authenticated (Admin only)"
      security: 
        - bearerAuth: []
      parameters: 
        - in: "query"
          name: "page"
          type: "integer"
          required: false
          default: 1
          description: "Page number" 
        
        - in: "query"
          name: "per_page"
          type: "integer"
          required: false
          default: 10
          description: "Number of users per page" 
      responses: 
        200: 
          description: "Retrieved users successfully"
          schema: 
            $ref: "#/definitions/AllUsers"

  /users/{id}:

    get: 
      tags: 
        - Users 
      summary: "Endpoint to get a specific user"
      description: "Returns a single user by ID, token authenticated, must be admin or the user themselves"
      security: 
        - bearerAuth: []
      parameters: 
        - in: "path"
          name: "id"
          type: "integer"
          required: true
          description: "User ID" 
      responses: 
        200: 
          description: "Retrieved user successfully"
          schema: 
            $ref: "#/definitions/GetUserResponse"
          examples: 
            application/json: 
              id: 1
              name: "John Doe" 
              email: "johndoe@gmail.com"
              role: "user"

    put: 
      tags: 
        - Users 
      summary: "Endpoint to update a user"
      description: "Endpoint to update a user, token authenticated, must be admin or user updating their own account"
      security: 
        - bearerAuth: []
      parameters: 
        - in: "path"
          name: "id"
          type: "integer"
          required: true
          description: "User ID" 

        - in: "body"
          name: "body"
          description: "Information required to update a user"
          required: true
          schema: 
            $ref: "#/definitions/UpdateUserPayload"
      responses: 
        200: 
          description: "Successfully updated user"
          schema: 
            $ref: "#/definitions/UpdateUserResponse"
          examples: 
            application/json: 
              id: 1
              name: Jane Doe
              email: janedoe123@gmail.com
              role: user 

    delete: 
      tags: 
        - Users 
      summary: "Endpoint to delete a user"
      description: "Endpoint to delete a user, token authenticated, must be admin or deleting their own account"
      security: 
        - bearerAuth: []
      parameters: 
        - in: "path"
          name: "id"
          type: "integer"
          required: true
          description: "User ID" 
      responses: 
        200: 
          description: "Successfully deleted user"
          schema: 
            $ref: "#/definitions/DeleteUserResponse"
          examples: 
            application/json: 
              message: "Successfully deleted user <user_id>"

  /subscriptions: 
        
    post: 
      tags: 
        - Subscriptions 
      summary: "Endpoint to create a new subscription"
      description: "Endpoint to create a new subscription, token authenticated, admin only"
      security: 
        - bearerAuth: []
      parameters: 
        - in: "body"
          name: "body"
          description: "Information required to create a new subscription"
          required: true
          schema: 
            $ref: "#/definitions/CreateSubscriptionPayload"
      responses: 
        201: 
          description: "Successful Subscription Creation"
          schema: 
            $ref: "#/definitions/CreateSubscriptionResponse"
          examples: 
            application/json: 
              id: 1
              user_id: 1
              plan_id: 1
              status: "active"
              start_date: "2026-04-10"

    get: 
      tags: 
        - Subscriptions 
      summary: "Endpoint to get all subscriptions"
      description: "Returns paginated list of all subscriptions, token authenticated (Admin only)"
      security: 
        - bearerAuth: []
      parameters: 
        - in: "query"
          name: "page"
          type: "integer"
          required: false
          default: 1
          description: "Page number" 
        
        - in: "query"
          name: "per_page"
          type: "integer"
          required: false
          default: 10
          description: "Number of subscriptions per page" 
      responses: 
        200: 
          description: "Retrieved subscriptions successfully"
          schema: 
            $ref: "#/definitions/AllSubscriptions"

  /subscriptions/{id}: 

    get: 
      tags: 
        - Subscriptions 
      summary: "Endpoint to get a specific subscription"
      description: "Returns a single subscription by ID, token authenticated, must be admin or the user themselves"
      security: 
        - bearerAuth: []
      parameters: 
        - in: "path"
          name: "id"
          type: "integer"
          required: true
          description: "Subscription ID" 
      responses: 
        200: 
          description: "Retrieved subscription successfully"
          schema: 
            $ref: "#/definitions/GetSubscriptionResponse"
          examples: 
            application/json: 
              id: 1
              user_id: 2
              plan_id: 1
              status: "active"
              start_date: "2026-04-10"

    put: 
      tags: 
        - Subscriptions 
      summary: "Endpoint to update a subscription"
      description: "Endpoint to update a subscription, token authenticated, must be admin or user updating their own account"
      security: 
        - bearerAuth: []
      parameters: 
        - in: "path"
          name: "id"
          type: "integer"
          required: true
          description: "Subscription ID" 

        - in: "body"
          name: "body"
          description: "Information required to update a subscription"
          required: true
          schema: 
            $ref: "#/definitions/UpdateSubscriptionPayload"
      responses: 
        200: 
          description: "Successfully updated subscription"
          schema: 
            $ref: "#/definitions/UpdateSubscriptionResponse"
          examples: 
            application/json: 
              id: 1
              user_id: 2
              plan_id: 1
              status: "Inactive"
              start_date: "2026-04-10" 

    delete: 
      tags: 
        - Subscriptions 
      summary: "Endpoint to delete a subscription"
      description: "Endpoint to delete a subscription, token authenticated, must be admin or deleting their own subscription"
      security: 
        - bearerAuth: []
      parameters: 
        - in: "path"
          name: "id"
          type: "integer"
          required: true
          description: "Subscription ID" 
      responses: 
        200: 
          description: "Successfully deleted subscription"
          schema: 
            $ref: "#/definitions/DeleteSubscriptionResponse"
          examples: 
            application/json: 
              message: "Successfully deleted subscription <subscription_id>"

  /plans: 
        
    post: 
      tags: 
        - Plans 
      summary: "Endpoint to create a new plan"
      description: "Endpoint to create a new plan, token authenticated, admin only"
      security: 
        - bearerAuth: []
      parameters: 
        - in: "body"
          name: "body"
          description: "Information required to create a new plan"
          required: true
          schema: 
            $ref: "#/definitions/CreatePlanPayload"
      responses: 
        201: 
          description: "Successful Plan Creation"
          schema: 
            $ref: "#/definitions/CreatePlanResponse"
          examples: 
            application/json: 
              id: 1
              name: "Verizon"
              price: 75.00
              billing_cycle: "monthly"

    get: 
      tags: 
        - Plans 
      summary: "Endpoint to get all plans"
      description: "Returns paginated list of all plans, token authenticated, must be logged in"
      security: 
        - bearerAuth: []
      parameters: 
        - in: "query"
          name: "page"
          type: "integer"
          required: false
          default: 1
          description: "Page number" 
        
        - in: "query"
          name: "per_page"
          type: "integer"
          required: false
          default: 10
          description: "Number of plans per page" 
      responses: 
        200: 
          description: "Retrieved plans successfully"
          schema: 
            $ref: "#/definitions/AllPlans"

  /plans/{id}: 

    get: 
      tags: 
        - Plans 
      summary: "Endpoint to get a specific plan"
      description: "Returns a single plan by ID, token authenticated, must be logged in"
      security: 
        - bearerAuth: []
      parameters: 
        - in: "path"
          name: "id"
          type: "integer"
          required: true
          description: "Plan ID" 
      responses: 
        200: 
          description: "Retrieved plan successfully"
          schema: 
            $ref: "#/definitions/GetPlanResponse"
          examples: 
            application/json: 
              id: 1
              name: "Verizon"
              price: 75.00
              billing_cycle: "monthly"

    put: 
      tags: 
        - Plans 
      summary: "Endpoint to update a plan"
      description: "Endpoint to update a plan, token authenticated, admin only"
      security: 
        - bearerAuth: []
      parameters: 
        - in: "path"
          name: "id"
          type: "integer"
          required: true
          description: "Plan ID" 

        - in: "body"
          name: "body"
          description: "Information required to update a plan"
          required: true
          schema: 
            $ref: "#/definitions/UpdatePlanPayload"
      responses: 
        200: 
          description: "Successfully updated plan"
          schema: 
            $ref: "#/definitions/UpdatePlanResponse"
          examples: 
            application/json: 
              id: 1
              name: "Verizon"
              price: 75.00
              billing_cycle: "monthly"

    delete: 
      tags: 
        - Plans 
      summary: "Endpoint to delete a plan"
      description: "Endpoint to delete a plan, token authenticated, admin only"
      security: 
        - bearerAuth: []
      parameters: 
        - in: "path"
          name: "id"
          type: "integer"
          required: true
          description: "Plan ID" 
      responses: 
        200: 
          description: "Successfully deleted plan"
          schema: 
            $ref: "#/definitions/DeletePlanResponse"
          examples: 
            application/json: 
              message: "Successfully deleted plan <plan_id>"

definitions: 

  LoginCredentials: 
    type: "object"
    properties: 
      email: 
        type: "string"
      password: 
        type: "string"
    
    required: 
      - email 
      - password 
  
  LoginResponse: 
    type: "object"
    properties: 
      token: 
        type: "string"
      message: 
        type: "string"
      status: 
        type: "string"
  
  CreateUserPayload: 
    type: "object"
    properties: 
      name: 
        type: "string"
      email:
        type: "string"
      password: 
        type: "string"
      role: 
        type: "string"
    
    required: 
      - name
      - email 
      - password 
      - role 
  
  CreateUserResponse: 
    type: "object"
    properties: 
      id: 
        type: "integer"
      name:
        type: "string"
      email: 
        type: "string"
      role: 
        type: "string"

  AllUsers: 
    type: "array"
    items: 
      type: "object"
      properties: 
        id: 
          type: "integer"
        name: 
          type: "string"
        email: 
          type: "string"
        role: 
          type: "string"

  GetUserResponse: 
    type: "object"
    properties: 
      id: 
        type: "integer"
      name:
        type: "string"
      email: 
        type: "string"
      role: 
        type: "string"

  UpdateUserPayload: 
    type: "object"
    properties: 
      name: 
        type: "string"
      email:
        type: "string"
      password: 
        type: "string"
      role: 
        type: "string"
  
  UpdateUserResponse: 
    type: "object"
    properties: 
      id: 
        type: "integer"
      name:
        type: "string"
      email: 
        type: "string"
      role: 
        type: "string"
  
  DeleteUserResponse: 
    type: "object"
    properties: 
      message: 
        type: "string"

  CreateSubscriptionPayload: 
    type: "object"
    properties: 
      user_id:
        type: "integer"
      plan_id: 
        type: "integer"
      status: 
        type: "string"
      start_date: 
        type: "string"
        format: "date"
    
    required: 
      - user_id
      - plan_id 
      - status
      - start_date 
  
  CreateSubscriptionResponse: 
    type: "object"
    properties: 
      id: 
        type: "integer"
      user_id:
        type: "integer"
      plan_id: 
        type: "integer"
      status: 
        type: "string"
      start_date: 
        type: "string"
        format: "date"
  
  AllSubscriptions: 
    type: "array"
    items: 
      type: "object"
      properties: 
        id: 
          type: "integer"
        user_id: 
          type: "integer"
        plan_id: 
          type: "integer"
        status: 
          type: "string"
        start_date: 
          type: "string"
          format: "date"
  
  GetSubscriptionResponse: 
    type: "object"
    properties: 
      id: 
        type: "integer"
      user_id:
        type: "integer"
      plan_id: 
        type: "integer"
      status: 
        type: "string"
      start_date: 
        type: "string"
        format: "date"
  
  UpdateSubscriptionPayload: 
    type: "object"
    properties: 
      user_id:
        type: "integer"
      plan_id: 
        type: "integer"
      status: 
        type: "string"
      start_date: 
        type: "string"
        format: "date"

  UpdateSubscriptionResponse: 
    type: "object"
    properties: 
      id: 
        type: "integer"
      user_id:
        type: "integer"
      plan_id: 
        type: "integer"
      status: 
        type: "string"
      start_date: 
        type: "string"
        format: "date"
  
  DeleteSubscriptionResponse: 
    type: "object"
    properties: 
      message: 
        type: "string"
  
  CreatePlanPayload: 
    type: "object"
    properties: 
      name: 
        type: "string"
      price:
        type: "number"
        format: "float"
      billing_cycle: 
        type: "string"
    
    required: 
      - name
      - price 
      - billing_cycle 
  
  CreatePlanResponse: 
    type: "object"
    properties: 
      id: 
        type: "integer"
      name:
        type: "string"
      price: 
        type: "number"
        format: "float"
      billing_cycle: 
        type: "string"

  AllPlans: 
    type: "array"
    items: 
      type: "object"
      properties: 
        id: 
          type: "integer"
        name:
          type: "string"
        price: 
          type: "number"
          format: "float"
        billing_cycle: 
          type: "string"
  
  GetPlanResponse: 
    type: "object"
    properties: 
      id: 
        type: "integer"
      name:
        type: "string"
      price: 
        type: "number"
        format: "float"
      billing_cycle: 
        type: "string"

  UpdatePlanPayload: 
    type: "object"
    properties: 
      name:
        type: "string"
      price: 
        type: "number"
        format: "float"
      billing_cycle: 
        type: "string"

  UpdatePlanResponse: 
    type: "object"
    properties: 
      id: 
        type: "integer"
      name:
        type: "string"
      price: 
        type: "number"
        format: "float"
      billing_cycle: 
        type: "string"
  
  DeletePlanResponse: 
    type: "object"
    properties: 
      message: 
        type: "string"